### ISSUE TITLE
Feature suggestion: Allow defining aliases in interactive mode

### ISSUE THREAD

**Issue by leotaku** [chatziko/lci#3]
Adding new aliases/identifiers in interactive mode could be a nice feature to have. Defining aliases while in a running interpreter seems to already work using the `Consult 'file'` command so I also don't think this should be very hard to implement. (I could of course be wrong here)

**Comment by chatziko** [comment]
Indeed it shouldn't be hard. PRs are welcome, of course.

**Comment by chatziko** [comment]
Fixed in master.

The problem was that lci was using a custom LL parser with limited capabilities (it started as a university assignment in which we had to implement our own parser :smile: ). This made it hard to combine eg alias declarations with terms.

Now I changed to [dparser](https://github.com/jplevyak/dparser), so we have full GLR power.

For instance, it was pretty easy to add support for `[a,b,c]` list notation, as syntactic sugar for `a:b:c:Nil`.
